### ISSUE TITLE
Missing Quantization & Colorimetry labels

### ISSUE THREAD

**Issue by dtatut** [imfug/delivery-schema#10]
In the latest version of the schema, the following labels seem to be missing:

Quantization:

QE.APP4.1
QE.APP4.2
(see SMPTE ST 2067-40:2016)

Colorimetry:

COLOR.8DPP 
(see SMPTE TSP 2121-1:2018)

The labels are required to specify App #4 & TSP2121-1 deliverables

**Comment by dtatut** [comment]
update: COLOR.8DPP will be deprecated once the amendment on App 2E for HLG will pass. Do we need to consider the addition of COLOR.8DPP anyways or drop this request and update the delivery schema with the upcoming COLOR.8 value? (@palemieux  : any guidance here will be appreciated)

**Comment by palemieux** [comment]
It is not clear whether the identifier will change. In the meantime I would keep COLOR.8DPP.

**Comment by dtatut** [comment]
@palemieux : thanks for clarifying this. For the current version we will go with COLOR8.DPP and deprecate it in the future if needed, due to a ST or TSP change.

**Comment by fschleich** [comment]
I added COLOR.8DPP and QE.APP4.1, but am not aware of QE.APP4.2. Where is it defined, @dtatut ?

**Comment by dtatut** [comment]
@fschleich : my mistake. I must have been reading a pre-publishing version of ST2067-40 where QE.APP4.2 was still present. Let's forget about it.

**Comment by dtatut** [comment]
fixed by @fschleich
