### ISSUE TITLE
inclusive vs exclusive

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [imfug/delivery-schema#19]
*exclusive*: one and only one value must be present
*inclusive*: one or more values may be present

Last time you explained, I saw it as:
You can mention many Applications any time.
But the inclusive include parent specification (like App2e includes App2).
And exclusive is to mention explicit values, so for an App2 the App2e requirement is not valid.

Regarding that definition, it will be more relevant with:
*exclusive*: an explicit list of IMF Applications is required
*inclusive*: a list of IMF Applications and it's inheritance are included

**Comment by dtatut** [comment]
for the ApplicationIdentificationList/MatchType element, 

1) the exclusive value means: among the values present in the list, only one of them can be present in the CPL. Basically the CPL is expected to carry one and only one instance of ApplicationIdentification.

2) the inclusive value means: one or more of the values listed can be present in the CPL. Basically the CPL is expected to carry one or more instances of ApplicationIdentification.

while App2E inherits its properties from App2, the ApplicationIdentification of App2 is not necessarily present in an App 2E CPL. Some use cases are apparently requiring App 2 & 2E ApplicationIdentification URIs. As far as I know these use cases are marginal, but that's what we wanted to support here.

I don't quite understand your comment though. What seems to be not working for you?

**Comment by dtatut** [comment]
@MarcAntoine-Arnaud : the documentation has been updated and hopefully it's a bit clearer now. Any feedback on your end? Let us know if this ticket can now be closed.

**Comment by MarcAntoine-Arnaud** [comment]
Looks good for me. Thanks @dtatut
