### ISSUE TITLE
Ambiguous elemet defintion in "VirtualTrackType"

### ISSUE THREAD

**Issue by Rico-Z** [imfug/delivery-schema#4]
The schema defines the complexType "VirtualTrackType". To distinguish between the different kinds (MainImageSequence, MainAudioSequence etc.) the "VirtualTrackType" defines an attribute named "kind". 

Further the "VirtualTrackType" defines elements for all possible kinds (e.g, "AudioChannelMapping", "Colorimetry"). This causes for instance that you can have in a XML instance a virtual track of kind "MainAudioSequence" which has an element "Colorimetry". This would not make sense but would be compliant to the schema.

Further some elements are defined as required and other as optional. At the moment the element "ImageFrameWidthList" is required. That causes that also in case of kind "MainAudioSequence" you have to include that "ImageFrameWidthList" element. 

I would suggest to solve that problem to use an inheritance / substitution structure for the different kinds of virtual tracks.

**Comment by Rico-Z** [comment]
Attached you find a proposal regarding the inheritance for the different VirtualTrackTypes.

I have defined one generic, abstract type for common properties. And further one AudioVirtualTrackType and one ImageVirtualTrackType which extends the generic one. 
Also attached one example how to use the different TrackTypes in a concrete XML document. 

Thank´s for any feedback.

[IMF_DeliverySchema_Inheritance-VirtualTrackType.zip](https://github.com/imfug/delivery-schema/files/2227616/IMF_DeliverySchema_Inheritance-VirtualTrackType.zip)

**Comment by IMFTool** [comment]
I agree with Rico: An inheritance based approach to derive specific kinds of VirtualTracks would limit the chance for semantic mistakes in delivery spec documents.
Are there any arguments not to accept his proposal ?

**Comment by dtatut** [comment]
as discussed during the call held on Jan. 25th, @fschleich + @IMFTool  are working on this fix

**Comment by dtatut** [comment]
This suggestion has been implemented in the XSD. Now, the documentation needs to reflect this change.
I'm closing this ticket and reopen a new one regarding the documentation update.
