### ISSUE TITLE
Meaningful names for elements and attributes

### ISSUE THREAD

**Issue by Rico-Z** [imfug/delivery-schema#5]
The "VirtualTrackType" defines an attribute named "kind" (kind of the sequence "MainImageSequence" etc.) and also an element named "Kind" (language?) which have different meanings. 

Therefore also the names of these two properties should be more differentiated.

**Comment by dtatut** [comment]
The kind attribute is deprecated and should be removed. Originally we used the attribute to identify the kind of the virtual track, but rapidly we agreed that we should stay away from attributes as they do not "map" well into structures in programming languages. The decision was made to use the Kind element instead.

**Comment by dtatut** [comment]
fixed
