### ISSUE TITLE
Limit visibility to repo while WIP?

### ISSUE THREAD

**Issue by ghost** [imfug/delivery-schema#6]
At our meeting in Munich I suggested that we keep this repo private while we are exploring and discussing options - the reason being that "the public" may mis-read or mis-represent our intentions and that *could* lead to unnecessary friction. Clearing those thingts up is just a waste of everybody's time :)
Bruce suggested that for groups like ours GitHub offers private repos at no cost?
If that is the case, I would propose that for now we make this repo private.

**Comment by dtatut** [comment]
for now the group can remain open as only active members contribute.

we can review this issue later if the group feels necessary to restrict access.
