### ISSUE TITLE
XSD requires 'import...dcml'?

### ISSUE THREAD

**Issue by ghost** [imfug/delivery-schema#7]
Oxygen failed to validate the XSD, and inserting 
`<xs:import namespace="http://www.smpte-ra.org/schemas/433/2008/dcmlTypes/" />`
after the xs:schema tag fixed it. 
I am fairly new to XSDs so I am not sure whether this is Oxygen being over-zealous or whether it is an actual bug?

**Comment by jhursty** [comment]
actual bug, thanks.

-jh

**Comment by ghost** [comment]
And fixed by Florian's update over the weekend, thanks!
