### ISSUE TITLE
XSD "complexType" contains direct element "MCATagSymbol"

### ISSUE THREAD

**Issue by ghost** [imfug/delivery-schema#8]
In the schema commit June 16 
Line 80 defines a complexType but
Line 81 defines an element

This appears to be invalid - even if there is only a single element, the complexType seems to require either "group","all","choice" or "sequence" first to contain the element(s)?

Sequence is probably as good as any other choice here? :-)

**Comment by fschleich** [comment]
Thanks Ulrich, fixed.

**Comment by ghost** [comment]
Crikey, you are quick!
I know that this should not have been an "Issue", instead I ought to have made a change and a "Pull Request" but... well, I have never done one of those and was a bit shy. Next time!
Thanks!
